export const STRIPE_PROVIDER_ID = "stripe" as const
export const STRIPE_DISPLAY_NAME = "Stripe"
export const STRIPE_API_BASE_URL = "https://api.stripe.com"
export const STRIPE_PAYMENT_INTENTS_PATH = "/v1/payment_intents"
export const STRIPE_ACCOUNTS_PATH = "/v1/accounts"
export const STRIPE_ACCOUNT_LINKS_PATH = "/v1/account_links"
export const STRIPE_ACCOUNT_SESSIONS_PATH = "/v1/account_sessions"
export const STRIPE_TERMINAL_LOCATIONS_PATH = "/v1/terminal/locations"
export const STRIPE_TERMINAL_READERS_PATH = "/v1/terminal/readers"
export const STRIPE_TERMINAL_CONNECTION_TOKENS_PATH = "/v1/terminal/connection_tokens"
export const STRIPE_TEST_HELPERS_TERMINAL_READERS_PATH = "/v1/test_helpers/terminal/readers"
export const STRIPE_SIGNATURE_HEADER = "stripe-signature"
export const STRIPE_WEBHOOK_TOLERANCE_SECONDS = 300
