import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import { generateReportEngine } from "./reports"

export async function generateReportPdfEngine(input: {
  merchantId: string
  startDate: string
  endDate: string
}) {
  const report = await generateReportEngine(input)

  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([620, 800])
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  let y = 760

  function draw(text: string, size = 12, boldText = false) {
    page.drawText(text, {
      x: 50,
      y,
      size,
      font: boldText ? bold : font,
      color: rgb(0, 0, 0)
    })
    y -= size + 6
  }

  function section(title: string) {
    y -= 10
    page.drawLine({
      start: { x: 50, y },
      end: { x: 570, y },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8)
    })
    y -= 18
    draw(title, 16, true)
    y -= 4
  }

  draw("PineTree Payments", 20, true)
  draw("Merchant Financial Report", 14)
  draw(`Date Range: ${input.startDate} → ${input.endDate}`, 10)
  y -= 10

  section("Financial Summary")
  draw(`Gross Volume: $${report.totalVolume.toFixed(2)}`)
  draw(`Transactions: ${report.transactionCount}`)
  draw(`Average Transaction: $${report.avgTransaction.toFixed(2)}`)
  draw(`Merchant Net: $${report.merchantNet.toFixed(2)}`)
  draw(`Estimated Taxes: $${report.estimatedTax.toFixed(2)}`)
  draw(`Failed Payments: ${report.failedPayments}`)

  section("Provider Breakdown")
  Object.entries(report.providerTotals).forEach(([provider, value]) => {
    draw(`${provider}: $${value.toFixed(2)}`)
  })

  section("Payment Channels")
  Object.entries(report.channelTotals).forEach(([channel, value]) => {
    draw(`${channel}: $${value.toFixed(2)}`)
  })

  section("Network Breakdown")
  Object.entries(report.networkTotals).forEach(([network, value]) => {
    draw(`${network}: $${value.toFixed(2)}`)
  })

  section("Transactions")
  draw("Date | Provider | Channel | Network | Amount", 11, true)
  y -= 4
  page.drawLine({ start: { x: 50, y }, end: { x: 570, y }, thickness: 1 })
  y -= 12

  report.transactionsTable.slice(0, 25).forEach((tx) => {
    const date = new Date(tx.date).toLocaleDateString()
    draw(`${date} | ${tx.provider} | ${tx.channel} | ${tx.network} | $${tx.amount.toFixed(2)}`, 10)
  })

  y -= 10
  draw(`Showing ${Math.min(report.transactionsTable.length, 25)} of ${report.transactionsTable.length} transactions`, 9)

  y = 40
  page.drawLine({
    start: { x: 50, y: 60 },
    end: { x: 570, y: 60 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85)
  })
  page.drawText("Generated by PineTree Payments", { x: 50, y: 40, size: 9, font })

  return pdfDoc.save()
}
