/**
 * Bridge (by Stripe) - the single shared server-only API client.
 *
 * Every Bridge REST call in PineTree goes through `bridgeRequest`. It owns URL
 * selection, required headers, idempotency, timeouts, response parsing, error
 * classification, and redaction. No route, component, engine module, or
 * wrapper may call fetch against Bridge directly.
 *
 * ── Authentication ───────────────────────────────────────────────────────────
 * Bridge authenticates with the `Api-Key` request header. It is NOT a Stripe
 * secret key and NOT a bearer token, and it never appears in a log, an error,
 * a return value, or a database row.
 *
 * ── Idempotency ──────────────────────────────────────────────────────────────
 * Bridge requires `Idempotency-Key` on mutating requests. PineTree ALWAYS
 * generates the key itself, deterministically, from the merchant and the
 * onboarding version - never from a client-supplied value and never randomly.
 * That is what makes a retried onboarding reuse the same Bridge customer
 * instead of creating a second one.
 *
 * ── Retry policy ─────────────────────────────────────────────────────────────
 * This client performs no automatic retries. A timeout leaves the outcome
 * UNKNOWN: Bridge may already have created the object. Resolution belongs to
 * the Engine, which retries with the SAME idempotency key or re-reads state.
 */

import { randomUUID } from "node:crypto"

import { getBridgeConfig, type BridgeConfig } from "./config"
import {
  BridgeApiError,
  BridgeInvalidResponseError,
  BridgeTransportError,
  type BridgeErrorDiagnostics,
} from "./errors"
import { bridgeSafeBodySummary, redactBridgePayload } from "./redact"
import type {
  BridgeBusinessCustomerPayload,
  BridgeCustomer,
  BridgeCustomerType,
  BridgeDrain,
  BridgeExternalAccount,
  BridgeKycLink,
  BridgeLiquidationAddress,
  BridgeLiquidationChain,
  BridgeWebhookEndpoint,
  NormalizedBridgeConnection,
} from "./types"
import { normalizeBridgeConnection } from "./normalize"

/**
 * Default request timeout. Bridge publishes no required timeout, so this is a
 * PineTree-chosen value for a control-plane (non-payment) call and is flagged
 * as such rather than presented as an official Bridge figure.
 */
export const BRIDGE_DEFAULT_TIMEOUT_MS = 20_000

function readPositiveIntEnv(name: string, fallback: number): number {
  const raw = String(process.env[name] || "").trim()
  if (!raw) return fallback
  const parsed = Number.parseInt(raw, 10)
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback
}

export function bridgeTimeoutMs(): number {
  return readPositiveIntEnv("BRIDGE_TIMEOUT_MS", BRIDGE_DEFAULT_TIMEOUT_MS)
}

/** PineTree context threaded through every request for correlation and logging. */
export type BridgeRequestContext = {
  correlationId?: string
  merchantId?: string | null
  merchantProviderConnectionId?: string | null
}

export type BridgeRequestOptions = {
  operation: string
  method: "GET" | "POST" | "PUT" | "DELETE"
  path: string
  body?: unknown
  /** Required for every mutating request. Generated by PineTree, never a client value. */
  idempotencyKey?: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
  timeoutMs?: number
}

export type BridgeRequestResult<T> = {
  data: T
  httpStatus: number
  correlationId: string
  /** Bridge's request identifier when the response carries one. */
  providerRequestId: string | null
  elapsedMs: number
}

const MUTATING_METHODS = new Set(["POST", "PUT", "DELETE"])

/**
 * True when a value contains a character that cannot safely appear in an HTTP
 * header: any control character (which includes CR and LF, the header-splitting
 * pair) or DEL.
 */
function hasUnsafeHeaderCharacter(value: string): boolean {
  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0
    if (codePoint < 0x20 || codePoint === 0x7f) return true
  }
  return false
}

export function assertUsableIdempotencyKey(key: string, operation: string): void {
  const normalized = String(key || "").trim()
  if (!normalized) {
    throw new BridgeApiError(`Bridge ${operation} requires a PineTree-generated idempotency key.`, {
      httpStatus: 400,
      code: "idempotency_key_required",
      diagnostics: { operation },
    })
  }
  if (normalized.length > 255 || hasUnsafeHeaderCharacter(normalized)) {
    throw new BridgeApiError(`Bridge ${operation} idempotency key is not a usable header value.`, {
      httpStatus: 400,
      code: "idempotency_key_invalid",
      diagnostics: { operation },
    })
  }
}

export function buildBridgeHeaders(input: {
  config: BridgeConfig
  idempotencyKey?: string
  hasBody: boolean
}): Record<string, string> {
  const headers: Record<string, string> = {
    // Bridge's documented authentication header. Exact casing per the docs.
    "Api-Key": input.config.apiKey,
    Accept: "application/json",
  }
  if (input.hasBody) headers["Content-Type"] = "application/json"
  if (input.idempotencyKey) headers["Idempotency-Key"] = input.idempotencyKey
  return headers
}

/** Bridge's correlation identifier, when present under any documented name. */
function extractProviderRequestId(response: Response): string | null {
  for (const name of ["x-request-id", "request-id", "x-bridge-request-id", "cf-ray"]) {
    const value = response.headers.get(name)
    if (value) return value
  }
  return null
}

function extractBridgeErrorCode(body: unknown): string | null {
  if (!body || typeof body !== "object") return null
  const record = body as Record<string, unknown>
  const code = record.code ?? (record.error as Record<string, unknown> | undefined)?.code
  const value = String(code ?? "").trim()
  return value || null
}

/**
 * Execute one Bridge REST request.
 *
 * Throws:
 *   BridgeTransportError       - no usable response (timeout / network)
 *   BridgeInvalidResponseError - 2xx body that is not usable JSON
 *   BridgeApiError             - configuration error or non-2xx provider response
 */
export async function bridgeRequest<T>(options: BridgeRequestOptions): Promise<BridgeRequestResult<T>> {
  const config = options.config ?? getBridgeConfig()
  const context = options.context ?? {}
  const correlationId = context.correlationId || randomUUID()
  const fetchImpl = options.fetchImpl ?? fetch
  const timeoutMs = options.timeoutMs ?? bridgeTimeoutMs()
  const hasBody = options.body !== undefined && MUTATING_METHODS.has(options.method)

  if (MUTATING_METHODS.has(options.method)) {
    assertUsableIdempotencyKey(options.idempotencyKey || "", options.operation)
  }

  const headers = buildBridgeHeaders({
    config,
    idempotencyKey: MUTATING_METHODS.has(options.method) ? options.idempotencyKey : undefined,
    hasBody,
  })

  const diagnostics: BridgeErrorDiagnostics = {
    operation: options.operation,
    correlationId,
    merchantId: context.merchantId ?? null,
    merchantProviderConnectionId: context.merchantProviderConnectionId ?? null,
    idempotencyKeyPresent: Boolean(options.idempotencyKey),
  }

  const url = `${config.baseUrl}${options.path}`
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  const startedAt = Date.now()

  let response: Response
  try {
    response = await fetchImpl(url, {
      method: options.method,
      headers,
      body: hasBody ? JSON.stringify(options.body) : undefined,
      signal: controller.signal,
    })
  } catch {
    const timedOut = controller.signal.aborted
    const elapsedMs = Date.now() - startedAt
    // A timeout after dispatch leaves the outcome UNKNOWN: Bridge may already
    // have created the customer. It is never a proven failure, and it must
    // never be resolved by resending with a fresh idempotency key.
    console.warn("[bridge] transport_failure", {
      ...diagnostics,
      timedOut,
      elapsedMs,
      outcomeClassification: timedOut ? "unknown_requires_state_reread" : "transport_failure",
    })
    throw new BridgeTransportError(
      timedOut ? "Bridge request timed out." : "Bridge is temporarily unreachable.",
      {
        timedOut,
        // A pre-dispatch connection failure did not reach Bridge, but for a
        // mutating operation PineTree cannot prove that, so uncertainty is
        // retained for those.
        outcomeUncertain: timedOut || MUTATING_METHODS.has(options.method),
        diagnostics: { ...diagnostics, elapsedMs },
      }
    )
  } finally {
    clearTimeout(timer)
  }

  const rawText = await response.text().catch(() => "")
  const elapsedMs = Date.now() - startedAt
  const providerRequestId = extractProviderRequestId(response)

  let parsed: unknown = null
  let jsonParsed = false
  if (rawText.trim()) {
    try {
      parsed = JSON.parse(rawText) as unknown
      jsonParsed = true
    } catch {
      jsonParsed = false
    }
  }

  if (!response.ok) {
    const summary = bridgeSafeBodySummary(rawText)
    console.warn("[bridge] api_error", {
      ...diagnostics,
      httpStatus: response.status,
      elapsedMs,
      providerRequestId,
      responseSummary: summary,
    })
    throw new BridgeApiError("Bridge rejected the request.", {
      httpStatus: response.status,
      code: extractBridgeErrorCode(parsed),
      diagnostics: {
        ...diagnostics,
        httpStatus: response.status,
        elapsedMs,
        providerRequestId,
        responseSummary: summary,
      },
    })
  }

  if (!jsonParsed || !parsed || typeof parsed !== "object") {
    const summary = bridgeSafeBodySummary(rawText)
    console.warn("[bridge] invalid_response", {
      ...diagnostics,
      httpStatus: response.status,
      elapsedMs,
      providerRequestId,
      outcomeClassification: "unknown_requires_state_reread",
      responseSummary: summary,
    })
    throw new BridgeInvalidResponseError("Bridge returned a response PineTree could not parse.", {
      ...diagnostics,
      httpStatus: response.status,
      elapsedMs,
      providerRequestId,
      responseSummary: summary,
    })
  }

  console.info("[bridge] operation_result", {
    ...diagnostics,
    httpStatus: response.status,
    elapsedMs,
    providerRequestId,
  })

  return {
    data: parsed as T,
    httpStatus: response.status,
    correlationId,
    providerRequestId,
    elapsedMs,
  }
}

function assertIdentifiedObject(
  value: unknown,
  operation: string,
  diagnostics: BridgeErrorDiagnostics
): void {
  const id = String((value as { id?: unknown } | null)?.id ?? "").trim()
  if (!id) {
    // A 2xx body with no id cannot be trusted as success for an operation whose
    // whole purpose is to yield a durable Bridge identifier.
    console.warn("[bridge] missing_identifier", {
      ...diagnostics,
      operation,
      responseSummary: bridgeSafeBodySummary(JSON.stringify(redactBridgePayload(value))),
    })
    throw new BridgeInvalidResponseError(`Bridge ${operation} response did not include an id.`, {
      ...diagnostics,
      operation,
    })
  }
}

/** URL-path segment escaping so a provider identifier can never alter the path. */
function pathSegment(value: string, operation: string): string {
  const normalized = String(value || "").trim()
  if (!normalized) {
    throw new BridgeApiError(`Bridge ${operation} requires an identifier.`, {
      httpStatus: 400,
      code: "identifier_required",
      diagnostics: { operation },
    })
  }
  return encodeURIComponent(normalized)
}

// ─── Operations ──────────────────────────────────────────────────────────────

export type CreateBridgeKycLinkInput = {
  /** For a business this is the full LEGAL business name, per Bridge's docs. */
  fullName: string
  email: string
  type: BridgeCustomerType
  /** Endorsements to request during onboarding, e.g. ["base"]. */
  endorsements?: string[]
  redirectUri?: string
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}

/**
 * Create a hosted Bridge KYC/KYB link.
 *
 * PineTree uses Bridge's hosted flow rather than rebuilding KYB collection, so
 * documents and personal identifiers go from the merchant's browser to Bridge
 * and never transit or rest in PineTree.
 */
export async function createKycLink(
  input: CreateBridgeKycLinkInput
): Promise<BridgeRequestResult<BridgeKycLink>> {
  const body: Record<string, unknown> = {
    full_name: input.fullName,
    email: input.email,
    type: input.type,
  }
  if (input.endorsements?.length) body.endorsements = input.endorsements
  if (input.redirectUri) body.redirect_uri = input.redirectUri

  const result = await bridgeRequest<BridgeKycLink>({
    operation: "create_kyc_link",
    method: "POST",
    path: "/kyc_links",
    body,
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })

  assertIdentifiedObject(result.data, "create_kyc_link", {
    correlationId: result.correlationId,
    merchantId: input.context?.merchantId ?? null,
  })
  return result
}

export async function getKycLink(input: {
  kycLinkId: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeKycLink>> {
  return bridgeRequest<BridgeKycLink>({
    operation: "get_kyc_link",
    method: "GET",
    path: `/kyc_links/${pathSegment(input.kycLinkId, "get_kyc_link")}`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

export async function getCustomer(input: {
  customerId: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeCustomer>> {
  return bridgeRequest<BridgeCustomer>({
    operation: "get_customer",
    method: "GET",
    path: `/customers/${pathSegment(input.customerId, "get_customer")}`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Create a Bridge business customer directly.
 *
 * This is the documented path for a platform that already holds the business
 * information: PineTree submits what the merchant entered once in their
 * PineTree Business Profile instead of sending them through a second hosted
 * KYB questionnaire.
 *
 * The payload carries KYB material. It is never logged here - the shared
 * request path redacts every diagnostic through redact.ts.
 */
export async function createCustomer(input: {
  payload: BridgeBusinessCustomerPayload
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeCustomer>> {
  const result = await bridgeRequest<BridgeCustomer>({
    operation: "create_customer",
    method: "POST",
    path: "/customers",
    body: input.payload,
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })

  assertIdentifiedObject(result.data, "create_customer", {
    correlationId: result.correlationId,
    merchantId: input.context?.merchantId ?? null,
  })
  return result
}

/**
 * Apply a partial update to an existing Bridge customer.
 *
 * A merchant editing their PineTree Business Profile updates the SAME Bridge
 * customer. PineTree never creates a second one for the same business.
 */
export async function updateCustomer(input: {
  customerId: string
  payload: Partial<BridgeBusinessCustomerPayload>
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeCustomer>> {
  return bridgeRequest<BridgeCustomer>({
    operation: "update_customer",
    method: "PUT",
    path: `/customers/${pathSegment(input.customerId, "update_customer")}`,
    body: input.payload,
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Retrieve the hosted KYB link for an EXISTING customer.
 *
 * PineTree creates the customer directly from the Business Profile, so this is
 * used only when Bridge still needs something it can collect but PineTree may
 * not hold - identity documents and similar. The URL is a bearer capability:
 * it is handed to the requesting merchant and never stored.
 */
export async function getHostedKycLinkForCustomer(input: {
  customerId: string
  redirectUri?: string
  endorsement?: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<{ url?: string; kyc_link?: string; tos_link?: string }>> {
  const params = new URLSearchParams()
  if (input.redirectUri) params.set("redirect_uri", input.redirectUri)
  if (input.endorsement) params.set("endorsement", input.endorsement)
  const query = params.toString() ? `?${params.toString()}` : ""

  return bridgeRequest<{ url?: string; kyc_link?: string; tos_link?: string }>({
    operation: "get_hosted_kyc_link",
    method: "GET",
    path: `/customers/${pathSegment(input.customerId, "get_hosted_kyc_link")}/kyc_link${query}`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Create a Bridge-hosted terms-of-service link.
 *
 * Bridge requires its own terms acceptance before KYB processing, and returns
 * the resulting `signed_agreement_id` on the redirect. The URL is a bearer
 * capability: it is handed straight back to the requesting merchant and never
 * stored.
 */
export async function createTosLink(input: {
  idempotencyKey: string
  redirectUri?: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<{ url?: string }>> {
  const query = input.redirectUri ? `?redirect_uri=${encodeURIComponent(input.redirectUri)}` : ""
  return bridgeRequest<{ url?: string }>({
    operation: "create_tos_link",
    method: "POST",
    path: `/customers/tos_links${query}`,
    body: {},
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Simulate KYB approval. SANDBOX ONLY.
 *
 * Bridge documents this endpoint as unavailable in production. The guard here
 * is a second line of defense: the Engine already refuses to call it outside
 * sandbox, and this refuses again from the configuration itself so no future
 * call site can reach production with it.
 */
export async function simulateKycApproval(input: {
  customerId: string
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeCustomer>> {
  const config = input.config ?? getBridgeConfig()
  if (config.environment !== "sandbox") {
    throw new BridgeApiError("Bridge KYB simulation is available in sandbox only.", {
      httpStatus: 403,
      code: "sandbox_only",
      diagnostics: { operation: "simulate_kyc_approval" },
    })
  }

  return bridgeRequest<BridgeCustomer>({
    operation: "simulate_kyc_approval",
    method: "POST",
    path: `/customers/${pathSegment(input.customerId, "simulate_kyc_approval")}/simulate_kyc_approval`,
    body: {},
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config,
    fetchImpl: input.fetchImpl,
  })
}

// ─── External accounts ───────────────────────────────────────────────────────

export type CreateBridgeUsExternalAccountInput = {
  customerId: string
  bankName: string
  accountName?: string
  accountOwnerName: string
  accountOwnerType: "business" | "individual"
  businessName?: string
  firstName?: string
  lastName?: string
  routingNumber: string
  accountNumber: string
  checkingOrSavings: "checking" | "savings"
  address: {
    street_line_1: string
    street_line_2?: string
    city: string
    state?: string
    postal_code?: string
    country: string
  }
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}

/**
 * Register a merchant's US bank account with Bridge.
 *
 * The raw account number exists only inside this call. PineTree persists the
 * Bridge external-account id and the masked last four that Bridge returns -
 * never the number itself.
 */
export async function createExternalAccount(
  input: CreateBridgeUsExternalAccountInput
): Promise<BridgeRequestResult<BridgeExternalAccount>> {
  const body: Record<string, unknown> = {
    account_type: "us",
    currency: "usd",
    bank_name: input.bankName,
    account_owner_name: input.accountOwnerName,
    account_owner_type: input.accountOwnerType,
    account: {
      routing_number: input.routingNumber,
      account_number: input.accountNumber,
      checking_or_savings: input.checkingOrSavings,
    },
    address: input.address,
  }
  if (input.accountName) body.account_name = input.accountName
  if (input.accountOwnerType === "business" && input.businessName) {
    body.business_name = input.businessName
  }
  if (input.accountOwnerType === "individual") {
    if (input.firstName) body.first_name = input.firstName
    if (input.lastName) body.last_name = input.lastName
  }

  const result = await bridgeRequest<BridgeExternalAccount>({
    operation: "create_external_account",
    method: "POST",
    path: `/customers/${pathSegment(input.customerId, "create_external_account")}/external_accounts`,
    body,
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })

  assertIdentifiedObject(result.data, "create_external_account", {
    correlationId: result.correlationId,
    merchantId: input.context?.merchantId ?? null,
  })
  return result
}

export async function listExternalAccounts(input: {
  customerId: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<{ data?: BridgeExternalAccount[] } | BridgeExternalAccount[]>> {
  return bridgeRequest<{ data?: BridgeExternalAccount[] } | BridgeExternalAccount[]>({
    operation: "list_external_accounts",
    method: "GET",
    path: `/customers/${pathSegment(input.customerId, "list_external_accounts")}/external_accounts`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Deactivate a merchant's bank destination at Bridge.
 *
 * Bridge's semantics are deactivate-not-delete, which preserves the payout
 * history that already references the account. PineTree mirrors that: the
 * PineTree row is archived, never removed.
 */
export async function deactivateExternalAccount(input: {
  customerId: string
  externalAccountId: string
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeExternalAccount>> {
  return bridgeRequest<BridgeExternalAccount>({
    operation: "deactivate_external_account",
    method: "POST",
    path:
      `/customers/${pathSegment(input.customerId, "deactivate_external_account")}` +
      `/external_accounts/${pathSegment(input.externalAccountId, "deactivate_external_account")}/deactivate`,
    body: {},
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

// ─── Liquidation addresses ───────────────────────────────────────────────────

export type CreateBridgeLiquidationAddressInput = {
  customerId: string
  chain: BridgeLiquidationChain
  currency: "usdc"
  externalAccountId: string
  destinationPaymentRail: "ach"
  destinationCurrency: "usd"
  /**
   * Where Bridge returns funds it cannot process. Bridge requires it to be on
   * the SAME source chain, so this is always the merchant's PineTree Wallet
   * address for that chain.
   */
  returnAddress: string
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}

export async function createLiquidationAddress(
  input: CreateBridgeLiquidationAddressInput
): Promise<BridgeRequestResult<BridgeLiquidationAddress>> {
  const result = await bridgeRequest<BridgeLiquidationAddress>({
    operation: "create_liquidation_address",
    method: "POST",
    path: `/customers/${pathSegment(input.customerId, "create_liquidation_address")}/liquidation_addresses`,
    body: {
      chain: input.chain,
      currency: input.currency,
      external_account_id: input.externalAccountId,
      destination_payment_rail: input.destinationPaymentRail,
      destination_currency: input.destinationCurrency,
      return_address: input.returnAddress,
    },
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })

  assertIdentifiedObject(result.data, "create_liquidation_address", {
    correlationId: result.correlationId,
    merchantId: input.context?.merchantId ?? null,
  })
  return result
}

export async function listLiquidationAddresses(input: {
  customerId: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<{ data?: BridgeLiquidationAddress[] } | BridgeLiquidationAddress[]>> {
  return bridgeRequest<{ data?: BridgeLiquidationAddress[] } | BridgeLiquidationAddress[]>({
    operation: "list_liquidation_addresses",
    method: "GET",
    path: `/customers/${pathSegment(input.customerId, "list_liquidation_addresses")}/liquidation_addresses`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/**
 * Drain history for one liquidation address.
 *
 * This is the AUTHORITATIVE payout evidence for a bank withdrawal: a source
 * chain receipt only proves the merchant's USDC reached Bridge.
 */
export async function listLiquidationAddressDrains(input: {
  customerId: string
  liquidationAddressId: string
  txHash?: string | null
  limit?: number
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<{ data?: BridgeDrain[] } | BridgeDrain[]>> {
  const params = new URLSearchParams()
  if (input.txHash) params.set("tx_hash", input.txHash)
  if (input.limit) params.set("limit", String(Math.min(Math.max(input.limit, 1), 100)))
  const query = params.toString() ? `?${params.toString()}` : ""

  return bridgeRequest<{ data?: BridgeDrain[] } | BridgeDrain[]>({
    operation: "list_liquidation_address_drains",
    method: "GET",
    path:
      `/customers/${pathSegment(input.customerId, "list_liquidation_address_drains")}` +
      `/liquidation_addresses/${pathSegment(input.liquidationAddressId, "list_liquidation_address_drains")}` +
      `/drains${query}`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}

/** Bridge list endpoints return either a bare array or `{ data: [...] }`. */
export function bridgeListItems<T>(payload: { data?: T[] } | T[] | null | undefined): T[] {
  if (Array.isArray(payload)) return payload
  if (payload && Array.isArray(payload.data)) return payload.data
  return []
}

/**
 * Read the merchant's current Bridge state from whichever identifiers exist.
 *
 * Returns the NORMALIZED connection; callers never see raw Bridge objects.
 * Both reads are attempted because the KYC link carries TOS acceptance while
 * the customer carries endorsements, and neither alone is sufficient.
 */
export async function syncCustomerStatus(input: {
  customerId?: string | null
  kycLinkId?: string | null
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<{ connection: NormalizedBridgeConnection; correlationId: string }> {
  const correlationId = input.context?.correlationId || randomUUID()
  const context = { ...input.context, correlationId }

  const kycLinkId = String(input.kycLinkId || "").trim()
  const customerIdFromInput = String(input.customerId || "").trim()

  let kycLink: BridgeKycLink | null = null
  if (kycLinkId) {
    const result = await getKycLink({ kycLinkId, context, config: input.config, fetchImpl: input.fetchImpl })
    kycLink = result.data
  }

  // The KYC link is what first reveals the customer id, so prefer the stored
  // id but fall back to the one Bridge just returned.
  const customerId = customerIdFromInput || String(kycLink?.customer_id || "").trim()

  let customer: BridgeCustomer | null = null
  if (customerId) {
    const result = await getCustomer({ customerId, context, config: input.config, fetchImpl: input.fetchImpl })
    customer = result.data
  }

  return { connection: normalizeBridgeConnection({ customer, kycLink }), correlationId }
}

/**
 * Read the merchant's normalized Bridge state. Named to match the universal
 * provider-connector contract; `syncCustomerStatus` is the Bridge-native name
 * for the same read.
 */
export async function getMerchantStatus(input: {
  customerId?: string | null
  kycLinkId?: string | null
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<NormalizedBridgeConnection> {
  const { connection } = await syncCustomerStatus(input)
  return connection
}

/**
 * Register a webhook endpoint with Bridge.
 *
 * PineTree does NOT provision webhooks automatically during onboarding: the
 * endpoint is a per-developer-account setting, not a per-merchant one, and
 * creating it from request paths would race across deployments. This helper
 * exists for one-time operator setup, and the Bridge Dashboard procedure is
 * documented in docs/environment/bridge-env-checklist.md.
 */
export async function createWebhook(input: {
  url: string
  idempotencyKey: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeWebhookEndpoint>> {
  const result = await bridgeRequest<BridgeWebhookEndpoint>({
    operation: "create_webhook",
    method: "POST",
    path: "/webhooks",
    body: { url: input.url },
    idempotencyKey: input.idempotencyKey,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })

  assertIdentifiedObject(result.data, "create_webhook", { correlationId: result.correlationId })
  return result
}

/**
 * Fetch a webhook endpoint's details, including the per-endpoint public key
 * used to verify `X-Webhook-Signature`.
 *
 * The returned key is verification material: it is used to configure
 * BRIDGE_WEBHOOK_PUBLIC_KEY and is never persisted to a database row or
 * returned to a browser.
 */
export async function fetchWebhookDetails(input: {
  webhookId: string
  context?: BridgeRequestContext
  config?: BridgeConfig
  fetchImpl?: typeof fetch
}): Promise<BridgeRequestResult<BridgeWebhookEndpoint>> {
  return bridgeRequest<BridgeWebhookEndpoint>({
    operation: "fetch_webhook_details",
    method: "GET",
    path: `/webhooks/${pathSegment(input.webhookId, "fetch_webhook_details")}`,
    context: input.context,
    config: input.config,
    fetchImpl: input.fetchImpl,
  })
}
