// Normalized from the two immutable Shift4 workbooks in PineTree-Shift4-Source.
export const workbookProvenance = Object.freeze({
  ecommerce: { file: "PineTree Ecom Test Script.xlsx", sha256: "B2020945C7257E34306BF44EB316083B11F8FCFDB2DF671972866FB00F7D82B1" },
  retail: { file: "PineTree Retail Test Script.xlsx", sha256: "0205015935BEFEEA46F5E980EFCEB1417455B85DAF02F51FE4B16AAC20D447E2" },
})

const c = (channel, sheet, test, name, expected, amountMinor = null, operations = []) =>
  Object.freeze({ id: `${channel}-${sheet.toLowerCase()}-${test}`, channel, sheet, test, name, expected, amountMinor, operations })

export const certificationCases = Object.freeze([
  c("ecommerce", "Evaluated", 1, "Access token exchange", "access_token_returned", null, ["access_token_exchange"]),
  c("ecommerce", "Evaluated", 2, "Multiple merchant IDs", "multiple_access_tokens_supported"),
  c("ecommerce", "Evaluated", 3, "Initial recurring authorization and capture", "approved", 11145, ["i4go", "authorization", "capture"]),
  c("ecommerce", "Evaluated", 4, "Subsequent recurring sale", "approved", 12500, ["sale"]),
  c("ecommerce", "Evaluated", 5, "Initial nonrecurring authorization and capture", "approved", 12600, ["i4go", "authorization", "capture"]),
  c("ecommerce", "Evaluated", 6, "Subsequent nonrecurring authorization and capture", "approved", 12700, ["authorization", "capture"]),
  c("ecommerce", "Evaluated", 7, "Void", "voided", null, ["void"]),
  c("ecommerce", "Evaluated", 8, "Refund decline", "declined", 1919, ["refund"]),
  c("ecommerce", "Evaluated", 9, "Timeout then approved invoice lookup", "approved_after_lookup", 11181, ["authorization", "invoice_lookup"]),
  c("ecommerce", "Evaluated", 10, "Invalid AVS", "declined_invalid_avs", 100, ["i4go", "authorization"]),
  c("ecommerce", "Evaluated", 11, "Invalid CSC", "declined_invalid_csc", 500, ["i4go", "authorization"]),
  c("ecommerce", "Evaluated", 12, "Split tender", "approved_and_captured", 50000, ["i4go", "authorization", "authorization", "capture", "capture"]),
  c("ecommerce", "Evaluated", 13, "Apple Pay tokenization", "approved_and_captured", 20000, ["apple_pay", "authorization", "capture"]),
  c("ecommerce", "Evaluated", 14, "Google Pay tokenization", "approved", 12500, ["google_pay", "sale"]),
  c("ecommerce", "Attest", 15, "Refund via token", "approved", 20000, ["refund"]),
  c("ecommerce", "Attest", 16, "Referral on initial authorization", "referral", 99999801, ["i4go", "authorization"]),
  c("ecommerce", "Attest", 17, "Decline on initial sale", "declined", 120000000, ["i4go", "sale"]),
  c("ecommerce", "Attest", 18, "Host error", "http_400", 3220200, ["i4go", "authorization"]),
  c("ecommerce", "Attest", 19, "Timeout referral", "referral_void_after_lookup", 51181, ["authorization", "invoice_lookup"]),
  c("ecommerce", "Attest", 20, "Timeout decline", "decline_void_after_lookup", 111181, ["sale", "invoice_lookup"]),
  c("ecommerce", "Attest", 21, "Timeout error", "error_void_after_lookup", 11281, ["authorization", "invoice_lookup"]),
  c("ecommerce", "Attest", 22, "Timeout blank response", "blank_response_after_lookup", 11295, ["sale", "invoice_lookup"]),
  c("ecommerce", "Attest", 23, "Invalid AVS and CSC", "declined_invalid_avs_csc", 13000, ["i4go", "authorization"]),

  c("retail", "Evaluated", 1, "Access token exchange", "access_token_returned", null, ["access_token_exchange"]),
  c("retail", "Evaluated", 2, "Multiple merchant IDs", "multiple_access_tokens_supported"),
  c("retail", "Evaluated", 3, "Authorization and full capture", "approved", 11145, ["authorization", "capture"]),
  c("retail", "Evaluated", 4, "Void", "voided", null, ["void"]),
  c("retail", "Evaluated", 5, "Refund via card", "approved", 10000, ["refund"]),
  c("retail", "Evaluated", 6, "Refund via token decline", "declined", 1919, ["refund"]),
  c("retail", "Evaluated", 7, "Referral then manual authorization and capture", "approved", 99999801, ["authorization", "merchant_information", "manual_authorization", "capture"]),
  c("retail", "Evaluated", 8, "Timeout then approved invoice lookup", "approved_after_lookup", 11161, ["authorization", "invoice_lookup"]),
  c("retail", "Evaluated", 9, "Partial authorization with second card", "approved_and_captured", 21900, ["authorization", "authorization", "capture", "capture"]),
  c("retail", "Evaluated", 10, "Partial authorization without second card", "voided", 21900, ["authorization", "void"]),
  c("retail", "Evaluated", 11, "Split tender", "approved_and_captured", 50000, ["authorization", "authorization", "capture", "capture"]),
  c("retail", "Evaluated", 12, "Debit approval", "approved", 11000, ["authorization"]),
  c("retail", "Evaluated", 13, "Invalid AVS and CSC", "declined_invalid_avs_csc", 13000, ["authorization"]),
  c("retail", "Evaluated", 14, "Invalid AVS", "declined_invalid_avs", 100, ["authorization"]),
  c("retail", "Evaluated", 15, "Invalid CSC", "declined_invalid_csc", 500, ["authorization"]),
  c("retail", "Evaluated", 16, "Valid AVS and CSC", "approved", 1000, ["authorization", "capture"]),
  c("retail", "Evaluated", 17, "POSHANDLEAVSFAIL invalid AVS", "approved_with_f_response", 100, ["authorization", "capture"]),
  c("retail", "Evaluated", 18, "POSHANDLEAVSFAIL invalid CSC", "approved_with_f_response_then_void", 500, ["authorization", "void"]),
  c("retail", "Attest", 19, "Referral without authorization code", "referral", 99999801, ["authorization"]),
  c("retail", "Attest", 20, "Decline", "declined", 120000000, ["authorization"]),
  c("retail", "Attest", 21, "Demo host error", "http_400", 3220200, ["authorization"]),
  c("retail", "Attest", 22, "Timeout referral", "referral_void_after_lookup", 51161, ["authorization", "invoice_lookup"]),
  c("retail", "Attest", 23, "Timeout decline", "decline_void_after_lookup", 111161, ["authorization", "invoice_lookup"]),
  c("retail", "Attest", 24, "Timeout error response", "error_void_after_lookup", 11261, ["authorization", "invoice_lookup"]),
  c("retail", "Attest", 25, "Timeout blank response", "blank_response_after_lookup", 11295, ["authorization", "invoice_lookup"]),
  c("retail", "Attest", 26, "Signature not captured", "approved_no_signature_9551_4", 15000, ["authorization"]),
])
