-- PineTree Shift4 database release postflight
-- static release-package validation; executable smoke SQL generated but not run locally; run after the pending sixth migration.
DO $postflight$
DECLARE
  v_name text;
  v_signature text;
  v_grantee text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY['ledger_accounts','ledger_transactions','ledger_journal_entries','ledger_links','shift4_tender_groups','shift4_payment_attempts','shift4_tokenization_sessions','shift4_onboarding_sessions','shift4_onboarding_events'] LOOP
    IF to_regclass('public.' || v_name) IS NULL THEN RAISE EXCEPTION 'Missing table: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_accounts_identity_uidx','ledger_accounts_owner_idx','ledger_transactions_posting_key_uidx','ledger_transactions_merchant_date_idx','ledger_transactions_reversal_idx','ledger_journal_entries_line_uidx','ledger_journal_entries_transaction_idx','ledger_journal_entries_account_idx','ledger_links_identity_uidx','ledger_links_payment_idx','ledger_links_merchant_idx','shift4_tender_groups_payment_connection_uidx','shift4_tender_groups_merchant_idx','shift4_payment_attempts_merchant_attempt_uidx','shift4_payment_attempts_connection_invoice_role_uidx','shift4_payment_attempts_connection_chain_invoice_uidx','shift4_payment_attempts_chain_root_uidx','shift4_payment_attempts_chain_idx','shift4_payment_attempts_tender_idx','shift4_payment_attempts_tender_group_idx','shift4_payment_attempts_connection_operation_idem_uidx','shift4_payment_attempts_payment_idx','shift4_payment_attempts_merchant_created_idx','shift4_payment_attempts_connection_created_idx','shift4_payment_attempts_authorization_idx','shift4_payment_attempts_related_idx','shift4_payment_attempts_recovery_state_idx','shift4_payment_attempts_due_work_idx','shift4_payment_attempts_active_lease_idx','shift4_tokenization_sessions_merchant_payment_idx','shift4_tokenization_sessions_expiry_idx','shift4_onboarding_sessions_merchant_created_idx','shift4_onboarding_sessions_status_idx','shift4_onboarding_events_session_received_idx','shift4_onboarding_events_merchant_received_idx'] LOOP
    IF to_regclass('public.' || v_name) IS NULL THEN RAISE EXCEPTION 'Missing index: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_history_is_immutable','ledger_account_identity_is_immutable','assert_ledger_transaction_balanced','resolve_ledger_account','post_ledger_transaction','shift4_tender_group_identity_is_immutable','shift4_tender_group_is_undeletable','shift4_canonical_status_path','shift4_status_event_type','create_shift4_payment_attempt','claim_due_shift4_payment_attempts','apply_shift4_attempt_evidence','release_shift4_attempt_lease','enforce_shift4_tokenization_session_ownership','consume_shift4_tokenization_session','shift4_onboarding_guard_ownership','shift4_onboarding_touch_updated_at','shift4_onboarding_events_immutable','create_shift4_onboarding_session','apply_shift4_onboarding_update'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=v_name) THEN RAISE EXCEPTION 'Missing function: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_transactions_immutable','ledger_accounts_identity_immutable','ledger_accounts_undeletable','ledger_journal_entries_immutable','ledger_links_immutable','ledger_journal_entries_balanced','shift4_tender_groups_identity_immutable','shift4_tender_groups_undeletable','shift4_tokenization_session_ownership','shift4_onboarding_sessions_ownership_trigger','shift4_onboarding_sessions_updated_at_trigger','shift4_onboarding_events_immutable_trigger'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname=v_name AND NOT tgisinternal) THEN RAISE EXCEPTION 'Missing trigger: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_accounts','ledger_transactions','ledger_journal_entries','ledger_links','shift4_tender_groups','shift4_payment_attempts','shift4_tokenization_sessions','shift4_onboarding_sessions','shift4_onboarding_events'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=v_name AND c.relrowsecurity) THEN RAISE EXCEPTION 'RLS missing: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_history_is_immutable()','ledger_account_identity_is_immutable()','assert_ledger_transaction_balanced()','resolve_ledger_account(text,text,text,text,text,text,integer)','post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)','shift4_canonical_status_path(text,text)','shift4_status_event_type(text)','shift4_tender_group_identity_is_immutable()','shift4_tender_group_is_undeletable()','create_shift4_payment_attempt(text,uuid,uuid,uuid,text,text,varchar,bigint,varchar,text,text,text,text,text,bigint,text,integer,text,text,text)','claim_due_shift4_payment_attempts(text,integer,integer,uuid,uuid,uuid,text,timestamptz)','apply_shift4_attempt_evidence(uuid,text,integer,text,text,text,text,text,integer,integer,text,text,text,text,text,text,text,text,text,text,text,bigint,bigint,timestamptz,timestamptz,text,text,timestamptz,timestamptz,boolean,boolean,boolean,boolean,text,text,text)','release_shift4_attempt_lease(uuid,text,text,timestamptz)','consume_shift4_tokenization_session(uuid,uuid,text,text)','enforce_shift4_tokenization_session_ownership()','shift4_onboarding_guard_ownership()','shift4_onboarding_touch_updated_at()','shift4_onboarding_events_immutable()','create_shift4_onboarding_session(uuid,uuid,text,text,text,text,text)','apply_shift4_onboarding_update(uuid,uuid,text,text,text,text,timestamptz,text,boolean,text)'] LOOP
    IF to_regprocedure('public.' || v_name) IS NULL THEN RAISE EXCEPTION 'Missing exact function signature: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['ledger_accounts_owner_type_check','ledger_accounts_account_type_check','ledger_accounts_currency_check','ledger_accounts_precision_check','ledger_accounts_status_check','ledger_transactions_posting_key_check','ledger_transactions_lifecycle_domain_check','ledger_transactions_currency_check','ledger_transactions_not_self_reversing_check','ledger_journal_entries_side_check','ledger_journal_entries_amount_check','ledger_journal_entries_line_number_check','ledger_journal_entries_currency_check','ledger_links_link_type_check','ledger_links_record_id_check','shift4_tender_groups_payment_fk','shift4_tender_groups_connection_fk','shift4_tender_groups_currency_check','shift4_tender_groups_requested_amount_check','shift4_tender_groups_next_sequence_check','shift4_tender_groups_state_check','shift4_payment_attempts_payment_fk','shift4_payment_attempts_connection_fk','shift4_payment_attempts_tender_group_fk','shift4_payment_attempts_operation_check','shift4_payment_attempts_channel_check','shift4_payment_attempts_attempt_role_check','shift4_payment_attempts_role_matches_operation_check','shift4_payment_attempts_chain_root_check','shift4_payment_attempts_tender_sequence_check','shift4_payment_attempts_tender_group_required_check','shift4_payment_attempts_remaining_amount_check','shift4_payment_attempts_partial_remainder_check','shift4_payment_attempts_manual_code_check','shift4_payment_attempts_state_check','shift4_payment_attempts_recovery_state_check','shift4_payment_attempts_timeout_classification_check','shift4_payment_attempts_currency_check','shift4_payment_attempts_invoice_check','shift4_payment_attempts_amount_minor_check','shift4_payment_attempts_approved_amount_minor_check','shift4_payment_attempts_authorized_amount_minor_check','shift4_payment_attempts_lookup_attempt_count_check','shift4_payment_attempts_resend_count_check','shift4_payment_attempts_attempt_number_check','shift4_payment_attempts_version_check','shift4_payment_attempts_capture_requires_authorization_check','shift4_payment_attempts_void_requires_related_check','shift4_payment_attempts_refund_requires_refund_id_check','shift4_payment_attempts_capture_lineage_alias_check','shift4_payment_attempts_capture_equals_authorization_check','shift4_payment_attempts_lease_pairing_check','shift4_onboarding_sessions_status_check','shift4_onboarding_sessions_application_unique','shift4_onboarding_sessions_launch_unique','shift4_onboarding_sessions_reason_safe','shift4_onboarding_sessions_hosted_url_safe','shift4_onboarding_sessions_correlation_present','shift4_onboarding_events_identity_unique','shift4_onboarding_events_status_check','shift4_onboarding_events_source_check','shift4_onboarding_events_reason_safe'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname=v_name) THEN RAISE EXCEPTION 'Missing constraint: %', v_name; END IF;
  END LOOP;
  FOREACH v_name IN ARRAY ARRAY['shift4_tokenization_sessions','shift4_onboarding_sessions','shift4_onboarding_events'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname=v_name AND c.relforcerowsecurity) THEN RAISE EXCEPTION 'FORCE RLS missing: %', v_name; END IF;
  END LOOP;
  IF to_regprocedure('public.consume_shift4_tokenization_session(uuid,uuid,text,text)') IS NULL THEN RAISE EXCEPTION 'Exact token-consumption RPC signature missing'; END IF;
  IF to_regprocedure('public.create_shift4_onboarding_session(uuid,uuid,text,text,text,text,text)') IS NULL THEN RAISE EXCEPTION 'Exact onboarding-create RPC signature missing'; END IF;
  IF to_regprocedure('public.apply_shift4_onboarding_update(uuid,uuid,text,text,text,text,timestamp with time zone,text,boolean,text)') IS NULL THEN RAISE EXCEPTION 'Exact onboarding-update RPC signature missing'; END IF;
  IF EXISTS (SELECT 1 FROM information_schema.role_table_grants WHERE table_schema='public' AND table_name='shift4_tokenization_sessions' AND grantee='service_role' AND privilege_type='UPDATE') THEN RAISE EXCEPTION 'service_role must consume tokenization sessions only through the RPC'; END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.column_privileges WHERE table_schema='public' AND table_name='shift4_tokenization_sessions' AND grantee='service_role' AND privilege_type='INSERT' AND column_name='session_id') THEN RAISE EXCEPTION 'service_role tokenization creation privilege missing'; END IF;
  IF EXISTS (SELECT 1 FROM information_schema.column_privileges WHERE table_schema='public' AND table_name='shift4_tokenization_sessions' AND grantee='service_role' AND privilege_type='INSERT' AND column_name IN ('token_fingerprint','consumed_at')) THEN RAISE EXCEPTION 'service_role tokenization INSERT columns are overprivileged'; END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname='public' AND p.proname IN ('ledger_history_is_immutable','ledger_account_identity_is_immutable','assert_ledger_transaction_balanced','resolve_ledger_account','post_ledger_transaction','shift4_tender_group_identity_is_immutable','shift4_tender_group_is_undeletable','shift4_canonical_status_path','shift4_status_event_type','create_shift4_payment_attempt','claim_due_shift4_payment_attempts','apply_shift4_attempt_evidence','release_shift4_attempt_lease','enforce_shift4_tokenization_session_ownership','consume_shift4_tokenization_session','shift4_onboarding_guard_ownership','shift4_onboarding_touch_updated_at','shift4_onboarding_events_immutable','create_shift4_onboarding_session','apply_shift4_onboarding_update') AND r.rolname IN ('PUBLIC','anon','authenticated','service_role')) THEN RAISE EXCEPTION 'Release function has unsafe owner role'; END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prosecdef AND p.proname IN ('ledger_history_is_immutable','ledger_account_identity_is_immutable','assert_ledger_transaction_balanced','resolve_ledger_account','post_ledger_transaction','shift4_tender_group_identity_is_immutable','shift4_tender_group_is_undeletable','shift4_canonical_status_path','shift4_status_event_type','create_shift4_payment_attempt','claim_due_shift4_payment_attempts','apply_shift4_attempt_evidence','release_shift4_attempt_lease','enforce_shift4_tokenization_session_ownership','consume_shift4_tokenization_session','shift4_onboarding_guard_ownership','shift4_onboarding_touch_updated_at','shift4_onboarding_events_immutable','create_shift4_onboarding_session','apply_shift4_onboarding_update') AND coalesce(array_to_string(p.proconfig,','),'') NOT LIKE '%search_path=%') THEN RAISE EXCEPTION 'SECURITY DEFINER function lacks pinned search_path'; END IF;
  IF EXISTS (SELECT 1 FROM information_schema.role_table_grants WHERE table_schema='public' AND table_name IN ('ledger_accounts','ledger_transactions','ledger_journal_entries','ledger_links','shift4_tender_groups','shift4_payment_attempts','shift4_tokenization_sessions','shift4_onboarding_sessions','shift4_onboarding_events') AND grantee IN ('anon','authenticated') AND privilege_type IN ('INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')) THEN RAISE EXCEPTION 'Unexpected browser write privilege'; END IF;
  SELECT p.proname, pg_get_function_identity_arguments(p.oid), coalesce(grantee.rolname, 'PUBLIC')
    INTO v_name, v_signature, v_grantee
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid=p.pronamespace
    CROSS JOIN LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) acl_entry
    LEFT JOIN pg_roles grantee ON grantee.oid=acl_entry.grantee
   WHERE n.nspname='public'
     AND p.proname IN ('ledger_history_is_immutable','ledger_account_identity_is_immutable','assert_ledger_transaction_balanced','resolve_ledger_account','post_ledger_transaction','shift4_tender_group_identity_is_immutable','shift4_tender_group_is_undeletable','shift4_canonical_status_path','shift4_status_event_type','create_shift4_payment_attempt','claim_due_shift4_payment_attempts','apply_shift4_attempt_evidence','release_shift4_attempt_lease','enforce_shift4_tokenization_session_ownership','consume_shift4_tokenization_session','shift4_onboarding_guard_ownership','shift4_onboarding_touch_updated_at','shift4_onboarding_events_immutable','create_shift4_onboarding_session','apply_shift4_onboarding_update')
     AND acl_entry.privilege_type='EXECUTE'
     AND coalesce(grantee.rolname, 'PUBLIC') IN ('PUBLIC','anon','authenticated')
   ORDER BY p.proname, pg_get_function_identity_arguments(p.oid), coalesce(grantee.rolname, 'PUBLIC')
   LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION 'Unexpected function EXECUTE privilege: public.%(%) grantee=%', v_name, v_signature, v_grantee;
  END IF;
  IF to_regprocedure('public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)') IS NULL THEN RAISE EXCEPTION 'Exact post_ledger_transaction signature missing'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_roles r ON r.oid=p.proowner WHERE p.oid=to_regprocedure('public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)') AND r.rolname='postgres') THEN RAISE EXCEPTION 'post_ledger_transaction owner must be postgres'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)') AND p.prosecdef) THEN RAISE EXCEPTION 'post_ledger_transaction must be SECURITY DEFINER'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_proc p WHERE p.oid=to_regprocedure('public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)') AND p.proconfig @> ARRAY['search_path=public, pg_temp']::text[]) THEN RAISE EXCEPTION 'post_ledger_transaction search_path must be pinned to public, pg_temp'; END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p CROSS JOIN LATERAL aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) acl_entry WHERE p.oid=to_regprocedure('public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)') AND acl_entry.grantee=0 AND acl_entry.privilege_type='EXECUTE') THEN RAISE EXCEPTION 'PUBLIC must not execute post_ledger_transaction'; END IF;
  IF has_function_privilege('anon', 'public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)', 'EXECUTE') OR has_function_privilege('authenticated', 'public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)', 'EXECUTE') THEN RAISE EXCEPTION 'Browser roles must not execute post_ledger_transaction'; END IF;
  IF NOT has_function_privilege('service_role', 'public.post_ledger_transaction(text,text,text,text,uuid,text,jsonb,jsonb,text,date,timestamptz,text,text,uuid,text,integer)', 'EXECUTE') THEN RAISE EXCEPTION 'service_role execute privilege missing for post_ledger_transaction'; END IF;
END;
$postflight$;
SELECT schemaname, tablename, policyname, roles, cmd, qual, with_check FROM pg_policies WHERE schemaname='public' AND tablename IN ('ledger_accounts','ledger_transactions','ledger_journal_entries','ledger_links','shift4_tender_groups','shift4_payment_attempts','shift4_tokenization_sessions','shift4_onboarding_sessions','shift4_onboarding_events') ORDER BY tablename, policyname;
SELECT n.nspname, p.proname, pg_get_function_identity_arguments(p.oid) AS signature, r.rolname AS owner, p.prosecdef, p.proconfig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname='public' AND p.proname IN ('ledger_history_is_immutable','ledger_account_identity_is_immutable','assert_ledger_transaction_balanced','resolve_ledger_account','post_ledger_transaction','shift4_tender_group_identity_is_immutable','shift4_tender_group_is_undeletable','shift4_canonical_status_path','shift4_status_event_type','create_shift4_payment_attempt','claim_due_shift4_payment_attempts','apply_shift4_attempt_evidence','release_shift4_attempt_lease','enforce_shift4_tokenization_session_ownership','consume_shift4_tokenization_session','shift4_onboarding_guard_ownership','shift4_onboarding_touch_updated_at','shift4_onboarding_events_immutable','create_shift4_onboarding_session','apply_shift4_onboarding_update') ORDER BY p.proname;
