import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

function read(relativePath: string) {
  return fs.readFileSync(path.join(process.cwd(), relativePath), "utf8")
}

describe("dashboard checkout and developer navigation", () => {
  it("adds distinct merchant and developer navigation entries", () => {
    const layout = read("app/dashboard/layout.tsx")

    expect(layout).toContain('{ name: "Online Checkout", href: "/dashboard/checkout" }')
    expect(layout).toContain('{ name: "Developer", href: "/dashboard/developer" }')
    expect(layout.indexOf('{ name: "Help Center", href: "/dashboard/help" }')).toBeLessThan(
      layout.indexOf('{ name: "Developer", href: "/dashboard/developer" }')
    )
    expect(layout.indexOf('{ name: "Developer", href: "/dashboard/developer" }')).toBeLessThan(
      layout.indexOf('{ name: "Settings", href: "/dashboard/settings" }')
    )
    expect(layout).not.toContain('description: "Create payment links')
    expect(layout).not.toContain('description: "API keys, webhooks')
  })

  it("keeps Online Checkout merchant-facing", () => {
    const checkout = read("app/dashboard/checkout/page.tsx")

    expect(checkout).not.toContain('"Create payment links and checkout buttons for customers."')
    expect(checkout).toContain("Create and share hosted checkout links.")
    expect(checkout).toContain("Add a checkout button to your website.")
    expect(checkout).toContain("checkoutReadinessStatus")
    expect(checkout).toContain("Set up checkout")
    expect(checkout).toContain("Getting paid online")
    expect(checkout).toContain("Payment Link Organization")
    expect(checkout).toContain("openMerchantDialog(card.target)")
    expect(checkout).toContain('aria-haspopup="dialog"')
    expect(checkout).toContain('role="dialog"')
    expect(checkout).toContain('aria-modal="true"')
    expect(checkout).toContain("h-[calc(100dvh_-_env(safe-area-inset-top)_-_0.75rem)]")
    expect(checkout).toContain("pt-[calc(env(safe-area-inset-top)_+_0.75rem)]")
    expect(checkout).toContain('data-pinetree-overlay="true"')
    expect(checkout).not.toContain('document.body.style.overflow = "hidden"')
    expect(checkout).toContain("previousFocus?.isConnected")
    expect(checkout).not.toContain("scrollIntoView")
    expect(checkout).not.toContain('href="#"')
    expect(checkout).toContain("Simple Setup")
    expect(checkout).toContain("Advanced Setup")
    expect(checkout).toContain('(["active", "disabled", "expired", "archived"] as LinkFilter[])')
    expect(checkout).toContain('body: JSON.stringify({ status: "archived" })')
    expect(checkout).toContain("Historical payments will remain intact.")
    expect(checkout).toContain('fieldId="merchant_html_button_snippet"')
    expect(checkout).toContain("Need API keys, webhooks, or SDKs?")
    expect(checkout).toContain('href="/dashboard/developer"')
    expect(checkout).toContain('mode === "developer" && tab === "webhooks"')
    expect(checkout).toContain('mode === "developer" && tab === "developer"')
  })

  it("uses compact Developer cards as the only section selector", () => {
    const developer = read("app/dashboard/developer/page.tsx")
    const publicKeys = read("app/dashboard/developer/PublicKeysPanel.tsx")
    const shopifyCard = [
      read("app/dashboard/developer/ShopifyIntegrationCard.tsx"),
      read("app/dashboard/developer/ShopifyIntegrationCardView.tsx"),
    ].join("\n")
    const wooCommerceCard = read("app/dashboard/developer/WooCommerceIntegrationCard.tsx")
    const checkout = read("app/dashboard/checkout/page.tsx")

    expect(developer).not.toContain("Manage API keys, webhooks, SDKs, and integrations.")
    expect(developer).not.toContain("const tabs")
    expect(developer).not.toContain("tabs.map")
    expect(developer).toContain("aria-pressed={tab === id}")
    expect(developer).toContain("<CheckoutWorkspace")
    expect(developer).toContain('mode="developer"')
    expect(developer).toContain("<PublicKeysPanel />")
    expect(developer).toContain("Getting Started")
    expect(developer).not.toContain("V1 Quick Start")
    expect(developer).not.toContain("v1 Quick Start")
    expect(developer).toContain("Node SDK")
    expect(developer).toContain("JavaScript SDK")
    expect(developer).toContain("React SDK")
    expect(developer.match(/status: "Ready"/g)).toHaveLength(4)
    expect(developer).toContain("No package required. Use a secret API key from your server to create checkout sessions.")
    expect(developer).toContain("WooCommerce")
    expect(developer).toContain("<WooCommerceIntegrationCard />")
    expect(developer).toContain('shopifyResult !== "connected"')
    expect(developer).toContain('setTab("integrations")')
    // WooCommerce card: merchant-facing, no GitHub links, actionable setup guide
    expect(wooCommerceCard).toContain('label="Not connected"')
    expect(wooCommerceCard).toContain("tone=\"slate\"")
    expect(wooCommerceCard).toContain("Install the PineTree WooCommerce plugin in a test store to validate checkout and webhooks.")
    expect(wooCommerceCard).toContain("View setup guide")
    expect(wooCommerceCard).toContain('id="woocommerce-setup-guide"')
    expect(wooCommerceCard).not.toContain("Open plugin folder")
    expect(wooCommerceCard).not.toContain("github.com")
    expect(wooCommerceCard).toContain("Download plugin")
    expect(wooCommerceCard).toContain("/api/woocommerce/plugin/download")
    expect(wooCommerceCard).toContain("Download the PineTree WooCommerce plugin from this dashboard.")
    expect(wooCommerceCard).not.toContain("onboarding contact")
    expect(wooCommerceCard).toContain("?wc-api=pinetree_webhook")
    expect(wooCommerceCard).toContain("Confirm the signed webhook updates the WooCommerce order.")
    expect(wooCommerceCard).toContain("does not duplicate notes or status changes")
    expect(wooCommerceCard).toContain("Use Manual sync")
    expect(wooCommerceCard).toContain('className="flex min-h-[4.5rem] items-start justify-between gap-3"')
    expect(wooCommerceCard).toContain('className="flex flex-1 flex-col pt-4"')
    expect(wooCommerceCard).toContain('className="mt-auto"')
    expect(wooCommerceCard).toContain('id="woocommerce-setup-guide" className="mt-4 border-t border-gray-100 pt-3"')
    // Shopify card: clean Connected/Not connected pattern, no ugly warning labels
    expect(shopifyCard).toContain("Connect a Shopify store to use PineTree Checkout.")
    expect(shopifyCard).toContain('label={connected ? "Connected" : "Not connected"}')
    expect(shopifyCard).toContain('tone={connected ? "blue" : "slate"}')
    expect(shopifyCard).toContain("Connect Shopify")
    expect(shopifyCard).toContain("Disconnect")
    expect(shopifyCard).toContain("View setup guide")
    expect(shopifyCard).not.toContain("Requires setup")
    expect(shopifyCard).not.toContain("OAuth")
    expect(shopifyCard).not.toContain("shopify_connections")
    expect(shopifyCard).not.toContain("/api/shopify/session")
    expect(shopifyCard).not.toContain("amber")
    expect(shopifyCard).toContain('className="flex min-h-[4.5rem] items-start justify-between gap-3"')
    expect(shopifyCard).toContain('className="flex flex-1 flex-col pt-4"')
    expect(shopifyCard).toContain('className="mt-auto pt-3"')
    expect(shopifyCard).toContain('id="shopify-setup-guide" className="mt-4 border-t border-gray-100 pt-3"')
    expect(developer).not.toContain("Foundation")
    expect(developer).not.toContain("Preview")
    expect(developer).not.toContain("Private Beta")
    expect(developer).toContain("npm install @pinetreepayments/node")
    expect(developer).toContain("npm install @pinetreepayments/js")
    expect(developer).toContain("npm install @pinetreepayments/react")
    expect(developer).toContain("rounded-xl border border-gray-200 bg-white")
    expect(developer).toContain("font-medium text-gray-950")
    expect(developer).not.toContain("bg-gray-950")
    expect(developer).not.toContain("text-emerald-400")
    expect(developer).not.toContain("publication pending")
    expect(developer).not.toContain("Installation commands will be available")
    expect(developer).not.toContain('label="Live"')
    // payments-v1 is the public webhook schema name and is allowed; block bare V1/v1 labels
    expect(developer).not.toMatch(/(?<![a-zA-Z\d-])v1\b|version one|PineTree API v1|\/api\/v1/i)
    expect(wooCommerceCard).not.toMatch(/(?<![a-zA-Z\d-])v1\b|internal checklist|backend checklist/i)
    expect(checkout).not.toContain("Failed attempts remain retryable through the v1 delivery API.")
    expect(checkout).not.toContain("V1 events also include")
    expect(checkout).toContain("Failed deliveries can be retried safely from this dashboard.")
    expect(checkout).toContain("Use <code className=\"font-mono\">pt_live_*</code> only on your server.")
    expect(developer).toContain("Use these only on your server. They can create sessions, retrieve payments, and manage webhooks.")
    expect(developer).toContain("Use these on websites, checkout buttons, or React apps.")
    expect(developer).toContain('setDocSection("quickstart")')
    expect(developer).toContain("Start quickstart")
    expect(developer).toContain("Create keys")
    expect(developer).toContain("Build checkout")
    expect(developer).toContain("Configure webhooks")
    expect(developer).toContain("Developer Status")
    expect(developer).toContain("Developer account setup and connection health.")
    expect(developer).toContain("Manage keys")
    expect(developer).toContain("Manage webhooks")
    expect(developer).toContain('<DashboardSection title="Documents" titleTone="blue">')
    expect(developer).toContain(">Documents</p>")
    expect(developer).toContain("<ApiReferencePanel activeDoc={docSection} setActiveDoc={setDocSection} />")
    expect(publicKeys).toContain("pk_live_*")
    expect(publicKeys).toContain("cannot access private account data")
    expect(publicKeys).toContain("/api/merchant/public-keys")
  })
})
